language: cpp
compiler: g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"

script:
    - cd src
    - make 
    - cd Assembler 
    - make 

notifications:
    email:
        - parth.kolekar@students.iiit.ac.in
        - anurag.ghosh@research.iiit.ac.in
